= How to change Influxdb passwords

== Root password

. Set new password in env file on S3 (s3://kontakt-telegraf-config/build-*/env), key `INFLUXDB_PASSWORD`.

. Set new password in BA database.

    [source,sql]
    ----
    UPDATE config_param SET value = 'NEW_PASSWORD' WHERE key = 'influxdb.root.password';
    ----

. Connect to Influx as root and set new password:

    [source]
    ----
    SET PASSWORD FOR "root" = 'NEW_PASSWORD'
    ----

. Set new password in Kapacitor, `/etc/kapacitor/kapacitor.conf` section `\[[influxdb]]`

. Restart all telegraf ECS tasks.

== Users password

. Set new password in env file on S3 (`s3://kontakt-telegraf-config/build-*/env`), key `INFLUXDB_NEW_USER_PASSWORD`.

. Set new password in BA database.

    [source,sql]
    ----
    UPDATE config_param SET value = 'INFLUXDB_NEW_USER_PASSWORD' WHERE key = 'influxdb.password';
    ----

. Execute link:telegraf/tools/ci-scripts/influx-passwords.sh[script] to change all passwords:

    [source]
    ----
    ./influx-passwords.sh -p ROOT_PASSWORD -n INFLUXDB_NEW_USER_PASSWORD -h testinflux.kontakt.io
    ----
